INSERT INTO tb_livro(NOME ,DESCRIPTION ,AUTOR ,DATA_DEVOLUCAO ,DATA_ALUGUEL ) VALUES ('Livro 1','Descrição','Autor','2022-05-06','2022-04-28');
INSERT INTO tb_aluno(MATRICULA,NOME) VALUES ('123456','Nome');
INSERT INTO tb_aluno_livro(ALUNO_ID ,LIVRO_ID  ) VALUES (1,1);